### ISSUE TITLE
Setup Automated Update PRs for keeping the "stable" up to date.

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/ember-new-output#1]
**Goal**
Reduce maintenance burden of forked repo
- still want manual intervention
  - name tied to merge of updates
  - allows the reviewer to verify changes before merge

**Setup**
- Bot: https://github.com/wei/pull (available in the GH Marketplace: https://github.com/apps/pull)
- The Repo needs to require a review on the target branch: 
   ![image](https://user-images.githubusercontent.com/199018/81508140-4b283300-92d0-11ea-97db-ee5a3e3cc187.png)
- a `.github/pull.yml` file configured as:
```yaml
version: "1"
rules:
  - base: stable
    upstream: ember-cli:stable
    # keeps the codesandbox-specific changes last
    mergeMethod: rebase
    # assignees / reviewers so that these people receive emails about the PRs if they're not watching the PR
    assignees:              # Optional
      - NullVoxPopuli
    reviewers:              # Optional
      - NullVoxPopuli
```
